language: python
python:
  - "3.9"
before_install:
  - python --version
  - pip install -U pip
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python src/test_kebele.py
  - python src/test_woreda.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
